import pandas as pd
import numpy as np
from pathlib import Path

# Internal imports
import save
import utils
from BlockSim.Main import blocksim

def simulator(dir_results, input_file, runs, variants_by_module):

    simulator_directory = save.create_simulator_directory(
        root_directory=dir_results
    )

    output_blocksim = simulator_directory / f"blocksim-{runs}x.csv"

    blocksim(input_file=input_file, output_file=str(output_blocksim), runs=runs)
    
    try:
        df = pd.read_csv(output_blocksim)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        return

    df_simulator_mean_std = utils.compute_mean_std(
        df=df, 
        group_by='variant',
        columns=["verify"],
    )

    print("\nFiles generated by simulations in BlockSim:")
    path_csv = simulator_directory / "blocksim-mean-std.csv"
    df_simulator_mean_std.to_csv(path_csv, index=False)
    print(output_blocksim)
    print(path_csv)
    
    return str(path_csv)
